using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Poppin.Models.Geocoding
{
				public static class StateTransforms
				{
								public static Dictionary<string, string> StatesWithCodes = new Dictionary<string, string>
								{
												{ "ALABAMA", "AL" },
												{ "ALASKA", "AK" },
												{ "AMERICAN SAMOA", "AS" },
												{ "ARIZONA", "AZ" },
												{ "ARKANSAS", "AR" },
												{ "CALIFORNIA", "CA" },
												{ "COLORADO", "CO" },
												{ "CONNECTICUT", "CT" },
												{ "DELAWARE", "DE" },
												{ "DISTRICT OF COLUMBIA", "DC" },
												{ "FLORIDA", "FL" },
												{ "GEORGIA", "GA" },
												{ "GUAM", "GU" },
												{ "HAWAII", "HI" },
												{ "IDAHO", "ID" },
												{ "ILLINOIS", "IL" },
												{ "INDIANA", "IN" },
												{ "IOWA", "IA" },
												{ "KANSAS", "KS" },
												{ "KENTUCKY", "KY" },
												{ "LOUISIANA", "LA" },
												{ "MAINE", "ME" },
												{ "MARYLAND", "MD" },
												{ "MASSACHUSETTS", "MA" },
												{ "MICHIGAN", "MI" },
												{ "MINNESOTA", "MN" },
												{ "MISSISSIPPI", "MS" },
												{ "MISSOURI", "MO" },
												{ "MONTANA", "MT" },
												{ "NEBRASKA", "NE" },
												{ "NEVADA", "NV" },
												{ "NEW HAMPSHIRE", "NH" },
												{ "NEW JERSEY", "NJ" },
												{ "NEW MEXICO", "NM" },
												{ "NEW YORK", "NY" },
												{ "NORTH CAROLINA", "NC" },
												{ "NORTH DAKOTA", "ND" },
												{ "NORTHERN MARIANA IS", "MP" },
												{ "OHIO", "OH" },
												{ "OKLAHOMA", "OK" },
												{ "OREGON", "OR" },
												{ "PENNSYLVANIA", "PA" },
												{ "PUERTO RICO", "PR" },
												{ "RHODE ISLAND", "RI" },
												{ "SOUTH CAROLINA", "SC" },
												{ "SOUTH DAKOTA", "SD" },
												{ "TENNESSEE", "TN" },
												{ "TEXAS", "TX" },
												{ "UTAH", "UT" },
												{ "VERMONT", "VT" },
												{ "VIRGINIA", "VA" },
												{ "VIRGIN ISLANDS", "VI" },
												{ "WASHINGTON", "WA" },
												{ "WEST VIRGINIA", "WV" },
												{ "WISCONSIN", "WI" },
												{ "WYOMING", "WY" }
								};

								public static string[] StateCodes = new[]
								{
												"AL",
												"AK",
												"AS",
												"AZ",
												"AR",
												"CA",
												"CO",
												"CT",
												"DE",
												"DC",
												"FL",
												"GA",
												"GU",
												"HI",
												"ID",
												"IL",
												"IN",
												"IA",
												"KS",
												"KY",
												"LA",
												"ME",
												"MD",
												"MA",
												"MI",
												"MN",
												"MS",
												"MO",
												"MT",
												"NE",
												"NV",
												"NH",
												"NJ",
												"NM",
												"NY",
												"NC",
												"ND",
												"MP",
												"OH",
												"OK",
												"OR",
												"PA",
												"PR",
												"RI",
												"SC",
												"SD",
												"TN",
												"TX",
												"UT",
												"VT",
												"VA",
												"VI",
												"WA",
												"WV",
												"WI",
												"WY"
								};
				}
}
